### PR TITLE
switch to bbolt

### PR DESCRIPTION
**Pull request by kwiesmueller**
https://github.com/djherbis/stow/issues/11

### CODE REVIEW

**Comment by djherbis** [comment]
This seems fine by me, thanks. One possible issue, since this technically is a breaking change I'll probably have to release it as a major version bump. (any issues with that?)

Also probably would have 'just worked' if boltdb had used type aliases to alias their types to the bbolt ones.

**Comment by djherbis** [comment]
Do you mind updating the README too?

**Comment by kwiesmueller** [comment]
Better?
And yes, it definitely should be a v3. No question.

**Comment by djherbis** [comment]
Thank you very much! :)

**Comment by kwiesmueller** [comment]
Thanks for reacting that quickly!
Even keeps me from using dep to fallback to my fork. Just awesome.

**Pull request merged**
